service: lkp-hello # To be replaced

configValidationMode: error

package:
  include:
    - src/

custom:
  esbuild:
    bundle: true
    minify: true
    target: node16
  localstack:
    debug: true
    autostart: false
    stages:
      - dev
    host: http://localstack
    edgePort: 4566
    lambda:
      mountCode: false
  dynamoTables:
    productsTableName: ${param:productsTableName}
    productsTableArn: ${param:productsTableArn}
    discountErpIdIndex: '${self:service}-${self:provider.stage}-discount-table-gsi'
    discountTableName: '${self:service}-${self:provider.stage}-discount-table'
    discountTableNameArn:
      Fn::GetAtt: ['DiscountTable', 'Arn']
  default:
    provider: ${file(../../serverless.common.yml):provider}
    plugins: ${file(../../serverless.common.yml):plugins}

plugins: ${self:custom.default.plugins}

provider:
  name: ${self:custom.default.provider.name}
  runtime: ${self:custom.default.provider.runtime}
  stage: ${self:custom.default.provider.stage}
  region: ${self:custom.default.provider.region}
  memorySize: ${self:custom.default.provider.memorySize}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:BatchWriteItem'
        - 'dynamodb:Query'
      Resource:
        - Fn::Join:
            [
              '/',
              [
                '${self:custom.dynamoTables.discountTableNameArn}',
                'index',
                '*',
              ],
            ]
        - ${self:custom.dynamoTables.discountTableNameArn}
        - Fn::Join:
            [
              '/',
              ['${self:custom.dynamoTables.productsTableArn}', 'index', '*'],
            ]
        - ${self:custom.dynamoTables.productsTableArn}

functions:
  hello:
    handler: src/lambda/hello.handler
    environment:
      productTable: ${self:custom.dynamoTables.productsTableName}
      discountTableName: ${self:custom.dynamoTables.discountTableName}
      discountErpIdIndex: ${self:custom.dynamoTables.discountErpIdIndex}

stepFunctions:
  validate: true
  stateMachines:
    hello:
      name: ${self:service}-hello
      definition:
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: Passthru
          Passthru:
            Type: Pass
            Next: Stop
          Stop:
            Type: Pass
            End: true
resources:
  Resources:
    DiscountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoTables.discountTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: erpId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: erpId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.dynamoTables.discountErpIdIndex}
            KeySchema:
              - AttributeName: erpId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
# S3BucketConfig:
#   Type: AWS::S3::Bucket
#   Properties:
#     BucketName: ${self:custom.s3.configBucket}
#   DeletionPolicy: Delete

# DBUsers:
#   Type: AWS::DynamoDB::Table
#   Properties:
#     TableName: usersTable
#     AttributeDefinitions:
#       - AttributeName: email
#         AttributeType: S
#     KeySchema:
#       - AttributeName: email
#         KeyType: HASH
#     ProvisionedThroughput:
#       ReadCapacityUnits: 1
#       WriteCapacityUnits: 1
