version: '3.2'

services:
  offline:
    image: aligent/serverless:offline
    command: serverless offline start --stage dev
    volumes: 
      - .:/app
      - ~/.npm:/home/node/.npm
      - ~/.aws:/home/node/.aws
