name: Test NX package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Test package building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npx nx g library test-lib --unitTestRunner=none
      - run: npx nx g service test-app
      # The next 2 lines are needed for nx affected to work when CI is running on a PR
      - uses: nrwl/nx-set-shas@v4
      - run: git branch --track main origin/main
      - run: npx nx affected -t lint, test, build --parallel=3 --base=origin/main
      - run: npx nx g rm test-lib
      - run: npx nx g rm test-app
