name: Test NX package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Test package building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npx nx g library test-lib --unitTestRunner=none
      - run: npx nx g service test-app
      - run: npx nx affected -t lint, test --parallel=2 --base=master
      - run: npx nx run-many -t build
