name: Test NX package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Test package building
    runs-on: ubuntu-latest
    env:
      # Generating an Nx library will cause a failure if this is enabled
      YARN_ENABLE_IMMUTABLE_INSTALLS: 0
    strategy:
      matrix:
        node-version: [22.14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate test library
        run: yarn nx g library test-lib --directory=libs/test-lib --unitTestRunner=none

      - name: Generate test app
        run: yarn nx g service test-app --type=general

      # The next 2 lines are needed for nx affected to work when CI is running on a PR
      - name: Set base SHA to origin/main
        uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4

      - name: Fetch main
        run: git fetch

      - name: Run tests
        run: yarn nx affected -t lint, typecheck, build --parallel=3 --base=origin/main

      - name: Remove test library
        run: yarn nx g rm @aligent/test-lib

      - name: Remove test app
        run: yarn nx g rm @services/test-app
